name: LighthouseCI
on:
    pull_request:

jobs:
    performance:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            - name: Install dependencies
              run: npm install && npm i -g http-server @lhci/cli

            - name: Build
              run: npm run build

            - name: LighthouseCI
              run: lhci autorun
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
